[package]
name = "chat_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.3.0"
mongodb = "2.0"
bson = "2.0"
futures = "0.3"
actix-cors = "0.7.0"